# workflowの名前
name: terraform plan 
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - '**.tf'

# https://tech.visasq.com/actions-pull-request-comment

jobs:
  comment-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 30
          ref: ${{ github.head_ref }}
      - id: diff-check
        if: github.event.action == 'synchronize'
        run: echo "diff-count=$(git diff ${{ github.event.before }} ${{ github.event.after }} --name-only --relative=test | wc -l)" >> $GITHUB_OUTPUT
      - id: no-diff-check
        if: github.event.action != 'synchronize'
        run: echo "diff-count=1" >> $GITHUB_OUTPUT
      - id: run 
        if: steps.diff-check.outputs.diff-count > 0 || steps.no-diff-check.outputs.diff-count > 0
        run: |
            DIR="$(git diff ${{ github.event.before }} ${{ github.event.after }} --name-only --relative=test | xargs dirname | sort | uniq)"
            wget https://github.com/mo3789530/tfupdate/releases/download/rc0.0.2/tfupdate
            sudo mv tfupdate /usr/local/bin
            sudo chmod +x /usr/local/bin/tfupdate
            echo $DIR
            tfupdate tf plan -d=$DIR -r=test/
